.TH GTKTerm "1" "September 15, 2019"
.\" Please adjust this date whenever revising the manpage.

.SH NAME
GTKTerm \- A simple GTK+ serial port terminal

.SH SYNOPSIS
.B gtkterm [ options ]

.SH DESCRIPTION
.B gtkterm 
is a simple GTK+ terminal used to communicate with the serial port.

.SH OPTIONS
.B gtkterm 
accepts the following options:

.B \-h, \-\-help 
Help screen.
.TP
.B \-c, \-\-config <configuration>
Load configuration (default is "default").
.TP
.B \-p, \-\-port <device>
Serial port device (default /dev/ttyS0).
.TP
.B \-s, \-\-speed <speed>
Serial port speed (default 9600).
.TP
.B \-b, \-\-bits <bits> 
Number of bits (default 8).
.TP
.B \-t, \-\-stopbits <stopbits>
Number of stopbits (default 1).
.TP
.B \-a, \-\-parity <odd | even> 
Partity (default none).
.TP
.B \-w, \-\-flow <Xon | CTS>
Flow control (default none).
.TP
.B \-d, \-\-delay <ms>
End of line delay in ms (default none).
.TP
.B \-r, \-\-char <char>
Wait for a special char at end of line (default none).
.TP
.B \-f, \-\-file <filename>
Default file to send (default none).
.TP
.B \-e, \-\-echo
Set local echo.
.TP
.B \-x, \-\-rts_time_before <ms>
For rs485, time in ms before transmit with rts on
.TP
.B \-y, \-\-rts_time_after <ms>
For rs485, time in ms after transmit with rts on
.TP
.B \-e, \-\-echo 
Switch on local echo
.TP
.B \-L, \-\-disable-port-lock
Do not lock serial port. Allows to send to serial port from different terminals.
.SH AUTHOR
.B gtkterm
was written by Julien Schmitt.
Maintained at https://github.com/Jeija/gtkterm by Willem van den Akker,
Florian Euchner

.PP
This manual page was written by Sebastien Bacher <seb128@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
